app/controllers/base_controller.rb
app/controllers/leave_applications_controller.rb
app/models/leave_application.rb
app/views/leave_applications/_form.html.haml
app/views/leave_applications/edit.html.haml
app/views/leave_applications/index.html.haml
app/views/leave_applications/new.html.haml
app/views/leave_applications/show.html.haml
config/locales/simple_form.zh_TW.yml

1. 實踐了 leave_applications 基本的 CRUD
2. 開始時間與結束時間的顯示方式需要再改
3. 還沒有做「主管審核」
4. LeaveApplication model 內需要新增 method，去自動計算 hours

realized basic leave_application CRUD

---

app/controllers/users/registrations_controller.rb
app/views/devise/shared/_links.html.erb
app/views/shared/_navigation.html.haml
config/routes.rb

如題 ww
hr/manager 進入 /users/sign_up 頁面則會顯示已經登入

restrict sign_up to whose access includes User resource

---

app/controllers/leave_applications_controller.rb
spec/controllers/leave_applications_controller_spec.rb
spec/factories/leave_applicaiton.rb
spec/factories/leave_times.rb
spec/factories/user.rb
spec/models/leave_application_spec.rb
spec/models/leave_time_spec.rb
spec/rails_helper.rb
spec/support/controller_macros.rb
spec/support/shared_response.rb

- Fix #may_cancel? control flow reversed error
- Add spec for LeaveApplicationController
- Add ControllerMacro for Device Login in Controller spec
- Add shared examples for load_and_authorize_resource failed response
- Adjust :leave_application factory
- Create object with user by default
- Add trait :with_leave_time to create object with LeaveTime

Add spec for LeaveApplicationController

---

.travis.yml
Gemfile
Gemfile.lock
config/secrets.yml.sample
spec/controllers/leave_applications_controller_spec.rb
spec/factories/user.rb
spec/spec_helper.rb

- Add DatabaseRewinder to truncate database tables between each tests.
- Add configuration file Travis CI

Travis CI setup

---

.gitignore
Gemfile
Gemfile.lock
db/migrate/20170330102550_add_remark_to_leave_time.rb
db/schema.rb

- 新增 :remark 欄位供註記休假額度給予之原因
- 新增 SeedFu 供過往休假紀錄匯入之用

Add :remark column to LeaveTime, Add SeedFu for data import

---

app/controllers/application_controller.rb
app/helpers/application_helper.rb
app/views/backend/users/_form.html.haml
app/views/devise/registrations/edit.html.haml
app/views/shared/_navigation.html.haml
config/locales/meta_data.zh_TW.yml
config/routes.rb

Issue-74 remove registration#edit email field by Eileen & Maxwell

Remove the email field from user registration#edit

---

app/services/leave_time_usage_builder.rb
spec/models/leave_application_spec.rb
spec/models/leave_time_spec.rb
spec/models/leave_time_usage_spec.rb

```ruby
LeaveTimeUsage.new(leave_application_instance).leave_hours_by_date
```

Issue #82 Divide LeaveApplication LeaveHours by date

---

.gitignore
app/models/leave_application.rb
app/models/leave_time.rb
app/models/leave_time_usage.rb
app/services/leave_time_usage_builder.rb

Revert "#94 將可以使用的 leave_times 之額度移到 locked_hours 並且產生 leave_time_usage 記錄"

---

app/helpers/application_helper.rb
app/views/backend/leave_applications/verify.html.haml
config/locales/meta_data.zh_TW.yml

1. 請假狀況顯示 "locked_hours" -> "圈存時數"
2. 審核假單顯示 "leave_hours_by_date" -> "每日請假時數"

display 'locked_hours' and 'leave_hours_by_date'

---

app/models/leave_application.rb
spec/models/leave_application_spec.rb

- Ensure minimum unit for LeaveApplication#hours is at least an hour
- Rewrite spec for this situation

Issue #114, Ensure minimum unit for LeaveApplication#hours is at least an hour

---

app/controllers/leave_applications_controller.rb
app/views/leave_applications/_form.html.haml
app/views/leave_applications/edit.html.haml
app/views/leave_applications/new.html.haml

#118 Fix bug which can let user send modified new application

---

app/controllers/backend/leave_applications_controller.rb
app/models/leave_application.rb
app/models/leave_time.rb
config/locales/meta_data.zh_TW.yml
spec/models/leave_time_spec.rb

#109 當假單通過時，會將 locked_hours 轉成 usable_hours

---

app/controllers/backend/leave_applications_controller.rb
app/controllers/leave_applications_controller.rb
app/models/leave_application.rb
app/models/leave_time.rb
config/locales/meta_data.zh_TW.yml
spec/models/leave_time_spec.rb

[待 #109 解決] #32 當假單被通過但還未發生時，可以取消假單

---

app/helpers/application_helper.rb
app/views/backend/leave_applications/index.html.haml
app/views/backend/leave_applications/verify.html.haml
app/views/leave_applications/index.html.haml
app/views/leave_applications/show.html.haml
app/views/shared/_leave_times_table.html.haml
config/locales/meta_data.zh_TW.yml
config/locales/zh_TW.yml

依照 #123 描述做修改，以下為這次 commit 做的修正：

#123 view revise

---

Gemfile
Gemfile.lock
app/controllers/backend/leave_times_controller.rb
app/models/leave_time.rb
app/views/backend/leave_times/index.html.haml
config/initializers/ransack.rb
config/locales/meta_data.zh_TW.yml
config/locales/pages.zh_TW.yml
config/locales/simple_form.zh_TW.yml
config/locales/zh_TW.yml

@Maxwell-Alexius @Eileen0917 請參照這個 PR 來讓其他頁面上的資料也可以被排序、篩選。
@Eileen0917 再麻煩針對需要修正的頁面開 Issue。

Use ransack to filter, sort data in Backend/LeaveTime#index

---

app/controllers/leave_times_controller.rb
app/views/leave_times/index.html.haml
config/locales/pages.zh_TW.yml

依照 #123 描述做修改，以下為這次 commit 做的修正：
查看請假額度 ( /leave_times )：頁面資料排序、篩選

#123 Use ransack to filter, sort data in LeaveTime#index

---

app/models/leave_time.rb
config/locales/meta_data.zh_TW.yml
spec/factories/leave_times.rb
spec/models/leave_time_spec.rb

#135 Add LeaveTime#balanced_hours Spec

---

app/controllers/leave_times_controller.rb
app/views/backend/leave_times/index.html.haml
app/views/backend/users/index.html.haml
app/views/backend/users/show.html.haml
app/views/leave_applications/show.html.haml
app/views/leave_times/index.html.haml
app/views/leave_times/show.html.haml
app/views/shared/_leave_times_table.html.haml
config/locales/pages.zh_TW.yml
config/locales/simple_form.zh_TW.yml
config/routes.rb

1. 將額度與假單之間做連結
- backend/users/show
- leave_applications/show
- leave_times/index
2. 修正 sum 的結果
原 locked_hour 下統計的為 used_hour；used_hour 下統計的為 locked_hour，現已調整成正確的加總。
- leave_times/index
- backend/leave_times/index
3. 調整 i18n

Display LeaveApplication mapping, fix display 'sum', and adjust i18n scope

---

Gemfile
Gemfile.lock
app/models/leave_application.rb
app/models/leave_application_observer.rb
app/models/leave_hours_by_date.rb
app/views/backend/leave_applications/verify.html.haml
app/views/leave_applications/show.html.haml
config/initializers/observer.rb
db/migrate/20170525103302_create_leave_hours_by_dates.rb
db/schema.rb
lib/tasks/import_data.rake
spec/factories/leave_hours_by_dates.rb
spec/models/leave_hours_by_date_spec.rb

- Implement ActiveRecord Import 來將大量 Insert 合為一次 SQL 處理
- Implement Rails::Observer 來幫忙管理 Model Callback

儲存每張假單的 LeaveHoursByDate (每日請假時數)

---

app/controllers/backend/leave_times_controller.rb
app/controllers/leave_applications_controller.rb
app/controllers/leave_times_controller.rb
app/controllers/remote_controller.rb
app/helpers/remote_helper.rb
app/models/application_record.rb
app/views/layouts/application.html.haml
app/views/leave_applications/_form.html.haml
app/views/remote/new.html.haml
app/views/shared/_navigation.html.haml
config/locales/meta_data.zh_TW.yml
config/locales/pages.zh_TW.yml
config/routes.rb
spec/controllers/remote_controller_spec.rb

issue #69 將申請 Remote 與一般請假做區分。

issue #69 differentiate remote and leave

---

app/models/leave_time.rb
app/views/leave_times/index.html.haml
spec/models/leave_time_spec.rb

Revert "#192 Exclude fullpaid_sick & halfpaid_sick Implementation"

---

Gemfile
Gemfile.lock
config/deploy.rb
config/environments/production.rb
config/fluent-logger.yml.example

增加 Fluent 支援，可以在公司的 Kibana 讀到 Production 上面的記錄。

Fluentd 支援

---

app/views/backend/leave_applications/index.html.haml

#224 fix the date display at backend/leave_application#index

---

app/controllers/backend/leave_times_controller.rb

issue#222 fix add leave_time when verify leave_application

---

app/controllers/backend/leave_times_controller.rb
app/views/pages/index.html.haml

issue #229

---

app/mailers/user_mailer.rb
app/views/mailers/user_mailer/reply_leave_applicaiton_email.html.haml
app/views/mailers/user_mailer/reply_leave_applicaiton_email.text.erb
config/locales/zh_TW.yml

issue #235 revise email content

---

app/assets/stylesheets/pages/backend/leave_applications.scss
app/controllers/backend/leave_applications_controller.rb
app/helpers/leave_applications_helper.rb
app/views/backend/leave_applications/statistics.html.haml

更新員工休假統計頁面
- 半薪病假/事假文字設成紅色
因為我不知道本來的寫法要怎樣改才會正確的算出時間,所以我整個寫法都改掉了

Feature/issue 239 需可查詢「某月份需要扣薪水的名單和時數」

---

app/helpers/application_helper.rb
app/views/backend/leave_applications/statistics.html.haml
config/locales/zh_TW.yml

將統計頁面的 “ x 天 x 小時（ x 小時）”，修正為 “ x 小時”

#239 修改小時顯示方式

---

app/views/backend/users/index.html.haml

issue #246 remove resigned user from backend/user#index

---

app/views/backend/users/show.html.haml
config/locales/zh_TW.yml

https://github.com/5xRuby/daikichi/issues/252

issue#252日期格式統一為 yyyy-mm-dd

---

app/controllers/leave_applications_controller.rb

更改歷年假單預設排序

---

app/views/leave_times/index.html.haml
config/application.yml.sample
config/locales/meta_data.zh_TW.yml
spec/factories/leave_applicaiton.rb
spec/models/leave_application_spec.rb
spec/services/leave_time_batch_builder_spec.rb
spec/services/leave_time_summary_service_spec.rb
spec/services/leave_time_usage_builder_spec.rb

issue #269 將病假拆成全新病假與半薪病假

---

app/services/leave_time_builder.rb
config/application.yml.sample
spec/models/user_spec.rb
spec/services/leave_time_batch_builder_spec.rb
spec/services/leave_time_builder_spec.rb

issue #223 weekly import remote

---

app/services/leave_time_batch_builder.rb
app/services/leave_time_builder.rb
spec/services/leave_time_batch_builder_spec.rb

fix leave time batch builder

---

app/controllers/backend/overtime_controller.rb
app/controllers/overtime_controller.rb
app/models/overtime.rb
app/models/user.rb
app/views/backend/overtime/_form.html.haml
app/views/backend/overtime/index.html.haml
app/views/backend/overtime/show.html.haml
app/views/backend/overtime/verify.html.haml
app/views/overtime/new.html.haml
app/views/shared/_leave_application_dropdown.html.haml
app/views/shared/_navigation.html.haml
config/locales/meta_data.zh_TW.yml
config/locales/pages.zh_TW.yml
config/locales/simple_form.zh_TW.yml
config/routes.rb
db/migrate/20180308103014_create_overtimes.rb
db/schema.rb
spec/factories/overtimes.rb
spec/models/overtime_spec.rb

Feature/issue 272/add bonus application

---

app/controllers/backend/leave_times_controller.rb
app/models/leave_application.rb
config/application.yml.sample
config/locales/meta_data.zh_TW.yml
config/locales/simple_form.zh_TW.yml
spec/features/leave_application/create_leave_application.rb

- 比照婚假, 喪假等特殊假，管理者審核時給予時數。
- 管理者審核特殊假，新增時數後轉跳回該筆假單審核頁面（前版為redirect至 /backend/leave_times）

issue 286: 新增員旅假功能

---

app/controllers/backend/leave_applications_controller.rb
app/controllers/backend/leave_times_controller.rb
spec/services/leave_time_batch_builder_spec.rb

排除已離職員工
- Filter out resigned employees in LeaveTime#index and LeaveApplication#index

更新審核假單、員工休假額度頁下拉選單選項
